defaults:
  logging_level_default: 5
# Use helm_values to set arbitrary helm values.
# These are passed through to the helm values file as-is.
# For example,
#
helm_values:
  # Null ParentTRL given by platform spec, currently the only place to do this.
  ska-tango-devices:
    deviceServers:
      pasd:
        smartbox-ci-1-sb01:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb01
        smartbox-ci-1-sb02:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb02
        smartbox-ci-1-sb03:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb03
        smartbox-ci-1-sb04:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb04
        smartbox-ci-1-sb05:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb05
        smartbox-ci-1-sb06:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb06
        smartbox-ci-1-sb07:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb07
        smartbox-ci-1-sb08:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb08
        smartbox-ci-1-sb09:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb09
        smartbox-ci-1-sb10:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb10
        smartbox-ci-1-sb11:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb11
        smartbox-ci-1-sb12:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb12
        smartbox-ci-1-sb13:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb13
        smartbox-ci-1-sb14:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb14
        smartbox-ci-1-sb15:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb15
        smartbox-ci-1-sb16:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb16
        smartbox-ci-1-sb17:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb17
        smartbox-ci-1-sb18:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb18
        smartbox-ci-1-sb19:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb19
        smartbox-ci-1-sb20:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb20
        smartbox-ci-1-sb21:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb21
        smartbox-ci-1-sb22:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb22
        smartbox-ci-1-sb23:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb23
        smartbox-ci-1-sb24:
            depends_on:
            - device: low-mccs/pasdbus/ci-1
            devices:
              MccsSmartbox:
              - low-mccs/smartbox/ci-1-sb24

    devices:
      MccsFieldStation:
        low-mccs/fieldstation/ci-1:
          ParentTRL: ""
      MccsPasdBus:
        low-mccs/pasdbus/ci-1:
          SmartboxIDs: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
      MccsSmartbox:
        low-mccs/smartbox/ci-1-sb01:
          AntennaNames: [sb01-01, sb01-02, sb01-03, sb01-04, sb01-05, sb01-06, sb01-07, sb01-08, sb01-09, sb01-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 1
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 1
        low-mccs/smartbox/ci-1-sb02:
          AntennaNames: [sb02-01, sb02-02, sb02-03, sb02-04, sb02-05, sb02-06, sb02-07, sb02-08, sb02-09, sb02-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 2
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 2
        low-mccs/smartbox/ci-1-sb03:
          AntennaNames: [sb03-01, sb03-02, sb03-03, sb03-04, sb03-05, sb03-06, sb03-07, sb03-08, sb03-09, sb03-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 3
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 3
        low-mccs/smartbox/ci-1-sb04:
          AntennaNames: [sb04-01, sb04-02, sb04-03, sb04-04, sb04-05, sb04-06, sb04-07, sb04-08, sb04-09, sb04-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 4
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 4
        low-mccs/smartbox/ci-1-sb05:
          AntennaNames: [sb05-01, sb05-02, sb05-03, sb05-04, sb05-05, sb05-06, sb05-07, sb05-08, sb05-09, sb05-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 5
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 5
        low-mccs/smartbox/ci-1-sb06:
          AntennaNames: [sb06-01, sb06-02, sb06-03, sb06-04, sb06-05, sb06-06, sb06-07, sb06-08, sb06-09, sb06-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 6
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 6
        low-mccs/smartbox/ci-1-sb07:
          AntennaNames: [sb07-01, sb07-02, sb07-03, sb07-04, sb07-05, sb07-06, sb07-07, sb07-08, sb07-09, sb07-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 7
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 7
        low-mccs/smartbox/ci-1-sb08:
          AntennaNames: [sb08-01, sb08-02, sb08-03, sb08-04, sb08-05, sb08-06, sb08-07, sb08-08, sb08-09, sb08-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 8
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 8
        low-mccs/smartbox/ci-1-sb09:
          AntennaNames: [sb09-01, sb09-02, sb09-03, sb09-04, sb09-05, sb09-06, sb09-07, sb09-08, sb09-09, sb09-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 9
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 9
        low-mccs/smartbox/ci-1-sb10:
          AntennaNames: [sb10-01, sb10-02, sb10-03, sb10-04, sb10-05, sb10-06, sb10-07, sb10-08, sb10-09, sb10-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 10
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 10
        low-mccs/smartbox/ci-1-sb11:
          AntennaNames: [sb11-01, sb11-02, sb11-03, sb11-04, sb11-05, sb11-06, sb11-07, sb11-08, sb11-09, sb11-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 11
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 11
        low-mccs/smartbox/ci-1-sb12:
          AntennaNames: [sb12-01, sb12-02, sb12-03, sb12-04, sb12-05, sb12-06, sb12-07, sb12-08, sb12-09, sb12-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 12
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 12
        low-mccs/smartbox/ci-1-sb13:
          AntennaNames: [sb13-01, sb13-02, sb13-03, sb13-04, sb13-05, sb13-06, sb13-07, sb13-08, sb13-09, sb13-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 13
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 13
        low-mccs/smartbox/ci-1-sb14:
          AntennaNames: [sb14-01, sb14-02, sb14-03, sb14-04, sb14-05, sb14-06, sb14-07, sb14-08, sb14-09, sb14-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 14
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 14
        low-mccs/smartbox/ci-1-sb15:
          AntennaNames: [sb15-01, sb15-02, sb15-03, sb15-04, sb15-05, sb15-06, sb15-07, sb15-08, sb15-09, sb15-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 15
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 15
        low-mccs/smartbox/ci-1-sb16:
          AntennaNames: [sb16-01, sb16-02, sb16-03, sb16-04, sb16-05, sb16-06, sb16-07, sb16-08, sb16-09, sb16-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 16
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 16
        low-mccs/smartbox/ci-1-sb17:
          AntennaNames: [sb17-01, sb17-02, sb17-03, sb17-04, sb17-05, sb17-06, sb17-07, sb17-08, sb17-09, sb17-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 17
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 17
        low-mccs/smartbox/ci-1-sb18:
          AntennaNames: [sb18-01, sb18-02, sb18-03, sb18-04, sb18-05, sb18-06, sb18-07, sb18-08, sb18-09, sb18-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 18
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 18
        low-mccs/smartbox/ci-1-sb19:
          AntennaNames: [sb19-01, sb19-02, sb19-03, sb19-04, sb19-05, sb19-06, sb19-07, sb19-08, sb19-09, sb19-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 19
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 19
        low-mccs/smartbox/ci-1-sb20:
          AntennaNames: [sb20-01, sb20-02, sb20-03, sb20-04, sb20-05, sb20-06, sb20-07, sb20-08, sb20-09, sb20-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 20
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 20
        low-mccs/smartbox/ci-1-sb21:
          AntennaNames: [sb21-01, sb21-02, sb21-03, sb21-04, sb21-05, sb21-06, sb21-07, sb21-08, sb21-09, sb21-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 21
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 21
        low-mccs/smartbox/ci-1-sb22:
          AntennaNames: [sb22-01, sb22-02, sb22-03, sb22-04, sb22-05, sb22-06, sb22-07, sb22-08, sb22-09, sb22-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 22
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 22
        low-mccs/smartbox/ci-1-sb23:
          AntennaNames: [sb23-01, sb23-02, sb23-03, sb23-04, sb23-05, sb23-06, sb23-07, sb23-08, sb23-09, sb23-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 23
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 23
        low-mccs/smartbox/ci-1-sb24:
          AntennaNames: [sb24-01, sb24-02, sb24-03, sb24-04, sb24-05, sb24-06, sb24-07, sb24-08, sb24-09, sb24-10]
          FieldStationName: low-mccs/fieldstation/ci-1
          FndhFQDN: low-mccs/fndh/ci-1
          FndhPort: 24
          ParentTRL: low-mccs/fieldstation/ci-1
          PasdFQDN: low-mccs/pasdbus/ci-1
          PortsWithAntennas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          SmartboxNumber: 24  


#   image:
#     registry: registry.gitlab.com/ska-telescope/mccs/ska-low-mccs-pasd
#     tag: 0.11.0-dev.cae7b6bc2
