overrides:
  array:
    station_clusters:
      "ci":
        stations:
          "1":
            id: 1
            pasd:
              fndh:
                gateway:
                  simulated: true
                  host: whatever
                  port: 9502  # >1024 so that simulator server can run unprivileged
                  timeout: 10.0
                controller:
                  modbus_id: 101
              smartboxes:
                "1":
                  fndh_port: 1
                  modbus_id: 1
            antennas:
              "100":
                location_offset:
                  east: -3.25
                  north: 11.478
                  up: 0.023
                eep: 100
                smartbox: "1"
                smartbox_port: 5
                tpm: "1"
                tpm_input: 5
              "113":
                location_offset:
                  east: -0.746
                  north: 12.648
                  up: 0.019
                eep: 113
                smartbox: "1"
                smartbox_port: 7
                tpm: "1"
                tpm_input: 7
              "121":
                location_offset:
                  east: -5.231
                  north: 12.066
                  up: 0.018
                eep: 121
                smartbox: "1"
                smartbox_port: 4
                tpm: "1"
                tpm_input: 4
              "134":
                location_offset:
                  east: -2.658
                  north: 13.574
                  up: 0.028
                eep: 134
                smartbox: "1"
                smartbox_port: 6
                tpm: "1"
                tpm_input: 6
              "155":
                location_offset:
                  east: -4.752
                  north: 14.09
                  up: 0.004
                eep: 155
                smartbox: "1"
                smartbox_port: 3
                tpm: "1"
                tpm_input: 3
              "168":
                location_offset:
                  east: -1.715
                  north: 15.36
                  up: 0.019
                eep: 168
                smartbox: "1"
                smartbox_port: 8
                tpm: "1"
                tpm_input: 8
              "189":
                location_offset:
                  east: -3.975
                  north: 15.948
                  up: 0.016
                eep: 189
                smartbox: "1"
                smartbox_port: 2
                tpm: "1"
                tpm_input: 2
              "202":
                location_offset:
                  east: -0.511
                  north: 16.966
                  up: 0.037
                eep: 202
                smartbox: "1"
                smartbox_port: 9
                tpm: "1"
                tpm_input: 9
              "223":
                location_offset:
                  east: -2.864
                  north: 17.596
                  up: 0.011
                eep: 223
                smartbox: "1"
                smartbox_port: 10
                tpm: "1"
                tpm_input: 10
              "244":
                location_offset:
                  east: -5.422
                  north: 17.79
                  up: 0.008
                eep: 244
                smartbox: "1"
                smartbox_port: 1
                tpm: "1"
                tpm_input: 1

defaults:
  logging_level_default: 5
