defaults:
  logging_level_default: 5

# Use helm_values to set arbitrary helm values.
# These are passed through to the helm values file as-is.
# For example,
#
# helm_values:
#   image:
#     registry: registry.gitlab.com/ska-telescope/mccs/ska-low-mccs-pasd
#     tag: 0.11.0-dev.cae7b6bc2
overrides:
  array:
    stations:
      "aavs3":
        id: 1
        pasd:
          config_uri: # Config uri currently breaks the functional tests
            uri: "gitlab://gitlab.com/ska-telescope/ska-low-aavs3?main#tmdata"
            path: "instrument/mccs-configuration/aavs3.yaml"
            station_name: "aavs3"