{{- /*
Deploy the Tango devices. For example,

  deviceServers:
    fieldstations:
      s8-1:
        low-mccs/fieldstation/s8-1:
          fndh_name: low-mccs/fndh/s8-1
          fncc_name: low-mccs/fncc/s8-1
          smartbox_names:
            - low-mccs/smartbox/s8-1-sb01
            - low-mccs/smartbox/s8-1-sb02
            - low-mccs/smartbox/s8-1-sb03
            - low-mccs/smartbox/s8-1-sb04
            - low-mccs/smartbox/s8-1-sb05
            - low-mccs/smartbox/s8-1-sb06
            - low-mccs/smartbox/s8-1-sb07
            - low-mccs/smartbox/s8-1-sb08
            - low-mccs/smartbox/s8-1-sb09
            - low-mccs/smartbox/s8-1-sb10
            - low-mccs/smartbox/s8-1-sb11
            - low-mccs/smartbox/s8-1-sb12
            - low-mccs/smartbox/s8-1-sb13
            - low-mccs/smartbox/s8-1-sb14
            - low-mccs/smartbox/s8-1-sb15
            - low-mccs/smartbox/s8-1-sb16
            - low-mccs/smartbox/s8-1-sb17
            - low-mccs/smartbox/s8-1-sb18
            - low-mccs/smartbox/s8-1-sb19
            - low-mccs/smartbox/s8-1-sb20
            - low-mccs/smartbox/s8-1-sb21
            - low-mccs/smartbox/s8-1-sb22
            - low-mccs/smartbox/s8-1-sb23
            - low-mccs/smartbox/s8-1-sb24
          logging_level_default: 5
    pasdbuses:
      s8-1:
        low-mccs/pasdbus/s8-1:
          host: 10.137.0.129
          port: 502
          timeout: 10
          logging_level_default: 5
    fndhs:
      s8-1:
        low-mccs/fndh/s8-1:
          pasdbus_name: low-mccs/pasdbus/s8-1
          logging_level_default: 5
    fnccs:
      s8-1:
        low-mccs/fncc/s8-1:
          pasdbus_name: low-mccs/pasdbus/s8-1
          logging_level_default: 5
    smartboxes:
      s8-1-sb01:
        low-mccs/smartbox/s8-1-sb01
          smartbox_number: 1
          fndh_name: low-mccs/fndh/s8-1
          fndh_port: 1
          pasdbus_name: low-mccs/pasdbus/s8-1
          logging_level_default: 5
*/}}
{{ $localchart := . }}

{{- range $key, $deviceserver := .Values.deviceServers }}

{{- $filedeviceserver := tpl ($.Files.Get (printf "data/%s.yaml" $key)) $ | fromYaml }}
{{- $name := $filedeviceserver.kubernetesName | default $key}}

{{- $context := dict "name" $name "deviceserver" $filedeviceserver "image" $filedeviceserver.image "local" $localchart}}
{{ template "ska-tango-util.multidevice-config.tpl" $context }}
{{ template "ska-tango-util.multidevice-sacc-role.tpl" $context }}
{{ template "ska-tango-util.multidevice-job.tpl" $context }}
{{ template "ska-tango-util.multidevice-svc.tpl" $context }}

{{- end }}
