{{- /*
Deploy the Tango devices. For example,

  deviceServers:
    fieldstation-s8-1:
      expose: true
      devices:
        MccsFieldStation:
          low-mccs/fieldstation/s8-1:
            StationName: s8-1
            FndhFQDN: low-mccs/fndh/s8-1
            FnccFQDN: low-mccs/fncc/s8-1
            SmartBoxFQDNs:
            - low-mccs/smartbox/s8-1-sb01
            - low-mccs/smartbox/s8-1-sb02
            - low-mccs/smartbox/s8-1-sb03
            - low-mccs/smartbox/s8-1-sb04
            - low-mccs/smartbox/s8-1-sb05
            - low-mccs/smartbox/s8-1-sb06
            - low-mccs/smartbox/s8-1-sb07
            - low-mccs/smartbox/s8-1-sb08
            - low-mccs/smartbox/s8-1-sb09
            - low-mccs/smartbox/s8-1-sb10
            - low-mccs/smartbox/s8-1-sb11
            - low-mccs/smartbox/s8-1-sb12
            - low-mccs/smartbox/s8-1-sb13
            - low-mccs/smartbox/s8-1-sb14
            - low-mccs/smartbox/s8-1-sb15
            - low-mccs/smartbox/s8-1-sb16
            - low-mccs/smartbox/s8-1-sb17
            - low-mccs/smartbox/s8-1-sb18
            - low-mccs/smartbox/s8-1-sb19
            - low-mccs/smartbox/s8-1-sb20
            - low-mccs/smartbox/s8-1-sb21
            - low-mccs/smartbox/s8-1-sb22
            - low-mccs/smartbox/s8-1-sb23
            - low-mccs/smartbox/s8-1-sb24
            LoggingLevelDefault: 5
            ConfigurationHost: pasd-configuration-service
            ConfigurationPort: 8081
    pasdbus-s8-1:
      devices:
        MccsPasdBus:
          low-mccs/pasdbus/s8-1:
            Host: 10.137.0.129
            Port: 502
            Timeout: 10
            LoggingLevelDefault: 5
    fndh-s8-1:
      depends_on:
      - device: low-mccs/pasdbus/s8-1
      devices:
        MccsFNDH:
          low-mccs/fndh/s8-1:
            PasdFQDN: low-mccs/pasdbus/itf1
            LoggingLevelDefault: 5
    fncc-s8-1:
      devices:
        MccsFncc:
          low-mccs/fncc/s8-1:
            PasdFQDN: low-mccs/pasdbus/s8-1
            LoggingLevelDefault: 5
    smartbox-s8-1-sb01:
      depends_on:
      - device: low-mccs/pasdbus/s8-1
      devices:
        MccsSmartbox:
          low-mccs/smartbox/s8-1-sb01:
            SmartboxNumber: 1
            FieldStationName: low-mccs/fieldstation/itf1
            FndhFQDN: low-mccs/fndh/itf1
            PasdFQDN: low-mccs/pasdbus/itf1
            LoggingLevelDefault: 5
*/}}
{{ $localchart := . }}
{{- if $.Values.deviceServers}}
{{- $filedeviceserver := tpl .Values.deviceServerDefinition . | fromYaml }}
{{- $context := dict "name" "mccs-pasd" "deviceserver" $filedeviceserver "image" $filedeviceserver.image "local" $localchart}}
{{ template "ska-tango-util.0.4.17.multidevice-config.tpl" $context }}
{{ template "ska-tango-util.0.4.17.multidevice-sacc-role.tpl" $context }}
{{ template "ska-tango-util.0.4.17.multidevice-job.tpl" $context }}
{{ template "ska-tango-util.0.4.17.multidevice-svc.tpl" $context }}
{{- end}}
