{{- $labels := coalesce .Values.global.labels .Values.labels "label:none" }}
{{- range $key, $value := ((.Values.simulators).pasdbuses)}}
---
apiVersion: v1
kind: Service
metadata:
  name: field-configuration-service-{{$key}}
  namespace: {{$.Release.Namespace}}
  labels:
    component: field-configuration-service-{{$key}}
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
  selector:
    component: field-configuration-service-{{$key}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: field-station-configurator-{{$key}}
  namespace: {{$.Release.Namespace}}
  labels:
    component: field-configuration-service-{{$key}}
spec:
  selector:
    matchLabels:
      component: field-configuration-service-{{$key}}
  replicas: 1
  serviceName: field-configuration-service-{{$key}}
  template:
    metadata:
      labels:
        component: field-configuration-service-{{$key}}
    spec:
      serviceAccountName: config-watcher-acc
      containers:
      - name: field-station-configurator-{{$key}}
        image: {{$.Values.image.registry}}/{{$.Values.image.name}}:{{$.Values.image.tag}}
        imagePullPolicy: IfNotPresent
        command: 
          - "FieldStationConfigurator"
        env:
          - name: STATION_NAME
            value: {{$key}}
          - name: NAMESPACE
            value: {{$.Release.Namespace}}
{{- end}}    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-watcher-role
  namespace: {{$.Release.Namespace}}
rules:
- apiGroups: [""]
  resources: ["pod", "configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-watcher-acc
  namespace: {{$.Release.Namespace}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-watcher-rolebind
  namespace: {{$.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: config-watcher-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: config-watcher-acc
  namespace: {{$.Release.Namespace}}
---