defaults:
  logging_level_default: 5

# Use helm_values to set arbitrary helm values.
# These are passed through to the helm values file as-is.
# For example,
#
helm_values:
  # Null ParentTRL given by platform spec, currently the only place to do this.
  ska-tango-devices:
    devices:
      MccsFieldStation:
        low-mccs/fieldstation/itf1:
          ParentTRL: ""
        low-mccs/fieldstation/itf2:
          ParentTRL: ""
#   image:
#     registry: registry.gitlab.com/ska-telescope/mccs/ska-low-mccs-pasd
#     tag: 0.11.0-dev.cae7b6bc2
