environments:
  minikube-ci:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?b2e4d536dcd136fdaf0f19c7c79e3c3c633895bb#tmdata
        datasets:
        - minikube/platform.yaml
      config_files:
      - values/values-ci.yaml
      datacentre: minikube
  stfc-ci:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?b2e4d536dcd136fdaf0f19c7c79e3c3c633895bb#tmdata
        datasets:
        - stfc-cloud/platform.yaml
      config_files:
      - values/values-ci.yaml
  aa0.5:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/ska-low-tmdata?979256650eff89261a2f1c9100cdc714310ca1b5#tmdata
        datasets:
        - aa0.5.yaml
        - stations/s8-1.yaml
        - stations/s8-6.yaml
        - stations/s9-1.yaml
        - stations/s9-2.yaml
        - stations/s10-3.yaml
      config_files:
      - values/values-aa0-5.yaml
      datacentre: infra:au-aa-mccs-cloud01-k8s
  low-itf:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/aiv/ska-low-itf?dcd7e0c4444e29ee2110379f3f2a4a4c9fd8c390#tmdata
        datasets:
        - low-itf.yaml
        - stations/itf1.yaml
        - stations/itf2.yaml
      config_files:
      - values/values-low-itf.yaml
      datacentre: infra:au-itf-k8s-master01-k8s

---

environments:
  {{.Environment.Name}}:
{{- with .Environment.Values | get "datacentre" ""}}
    kubeContext: {{.}}
{{- end}}
    values:
      - .deploy/helmfile.d/templates/tmdata.yaml.gotmpl
      {{- toYaml .Environment.Values.config_files | nindent 6}}

---

repositories:
  - name: skao
    url: https://artefact.skao.int/repository/helm-internal
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jupyterhub
    url: https://jupyterhub.github.io/helm-chart


releases:
  - name: ska-low-mccs-pasd
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: ../charts/ska-low-mccs-pasd
    values:
      - .deploy/helmfile.d/templates/globals.yaml.gotmpl
      - .deploy/helmfile.d/templates/pasd/fieldstations.yaml.gotmpl
      - .deploy/helmfile.d/templates/pasd/fnccs.yaml.gotmpl
      - .deploy/helmfile.d/templates/pasd/fndhs.yaml.gotmpl
      - .deploy/helmfile.d/templates/pasd/pasdbuses.yaml.gotmpl
      - .deploy/helmfile.d/templates/pasd/pasdconfiguration.yaml.gotmpl
      - .deploy/helmfile.d/templates/pasd/smartboxes.yaml.gotmpl
      - .deploy/helmfile.d/templates/helm-values.yaml.gotmpl

{{- $_tango_host_provided := dig "platform" "cluster" "services" "tango-base" "tango-host" "" .Values}}
{{- $tango_host_provided := dig "overrides" "cluster" "services" "tango-base" "tango-host" $_tango_host_provided .Values}}
{{- if not $tango_host_provided}}
  - name: ska-tango-base
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-base
    version: ~0.4.7
    values:
      - .deploy/helmfile.d/templates/globals.yaml.gotmpl
{{- end}}

{{- $_jupyterhub_provided := dig "platform" "cluster" "services" "jupyterhub" false .Values}}
{{- $jupyterhub_provided := dig "overrides" "cluster" "services" "jupyterhub" $_jupyterhub_provided .Values}}
{{- if not $jupyterhub_provided}}
  - name: jupyterhub
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: jupyterhub/jupyterhub
    version: 3.0.0
    values:
      - .deploy/helmfile.d/templates/jupyterhub.yaml
{{- end}}

{{- $_taranta_platform_provided := dig "platform" "cluster" "services" "taranta-platform" false .Values}}
{{- $taranta_platform_provided := dig "overrides" "cluster" "services" "taranta-platform" $_taranta_platform_provided .Values}}
{{- if not $taranta_platform_provided}}
  - name: taranta-dshbrd
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-taranta-dashboard
    version: 1.4.1
    values:
      - ingress:
          enabled: true
          hostname: "*"

  - name: taranta-dashboard-pvc
    namespace: ska-low-mccs
    chart: skao/ska-tango-taranta-dashboard-pvc
    version: 1.4.1

  - name: taranta-auth
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-taranta-auth
    version: ~0.1.9
    values:
      - ingress:
          enabled: true
          hostname: "*"
{{- end}}

  - name: taranta
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-taranta
    version: ~2.5.1
    values:
      - .deploy/helmfile.d/templates/taranta.yaml

  - name: tangogql
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-tangogql
    version: ~1.3.10
    values:
      - .deploy/helmfile.d/templates/globals.yaml.gotmpl
      - ska-tango-base:
          enabled: false
