environments:
  default:
    kubeContext: minikube
    values:
      - platform/minikube.yaml
  minikube:
    values:
      - platform/minikube.yaml
      - pasd/values/values-ci.yaml
  stfc-ci:
    values:
      - platform/stfc-ci.yaml
      - pasd/values/values-ci.yaml
  aa0.5-production:
    kubeContext: infra:au-aa-mccs-cloud01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/aa0.5.yaml?ref=4f49b0fa3dd3452cc155c4f7e6b321dd5b4025ac
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s8-1.yaml?ref=4f49b0fa3dd3452cc155c4f7e6b321dd5b4025ac
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s8-6.yaml?ref=4f49b0fa3dd3452cc155c4f7e6b321dd5b4025ac
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s9-2.yaml?ref=4f49b0fa3dd3452cc155c4f7e6b321dd5b4025ac
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s10-3.yaml?ref=4f49b0fa3dd3452cc155c4f7e6b321dd5b4025ac
      - pasd/values/values-aa0-5.yaml
  aa0.5-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/aa0.5.yaml?ref=4f49b0fa3dd3452cc155c4f7e6b321dd5b4025ac
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s8-1.yaml?ref=4f49b0fa3dd3452cc155c4f7e6b321dd5b4025ac
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s8-6.yaml?ref=4f49b0fa3dd3452cc155c4f7e6b321dd5b4025ac
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s9-2.yaml?ref=4f49b0fa3dd3452cc155c4f7e6b321dd5b4025ac
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@helmfile.d/platform/low/s10-3.yaml?ref=4f49b0fa3dd3452cc155c4f7e6b321dd5b4025ac
      - pasd/values/values-aa0-5.yaml
      - platform/minikube.yaml
  aavs3-production:
    kubeContext: infra:au-itf-aavs302-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=a8d7b124d965a0fa399bd7ab5462bc1bbacddedd
      - pasd/values/values-aavs3.yaml
  aavs3-staging:
    kubeContext: infra:au-itf-k8s-master01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=a8d7b124d965a0fa399bd7ab5462bc1bbacddedd
      - pasd/values/values-aavs3.yaml
      - pasd/values/values-aavs3-staging.yaml
  aavs3-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=a8d7b124d965a0fa399bd7ab5462bc1bbacddedd
      - pasd/values/values-aavs3.yaml
      - platform/minikube.yaml
  low-itf:
    kubeContext: infra:au-itf-k8s-master01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=61fc26cb3ac68be35e0fbf3fbfc73bf31435c805
      - pasd/values/values-low-itf.yaml
  low-itf-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=61fc26cb3ac68be35e0fbf3fbfc73bf31435c805
      - pasd/values/values-low-itf.yaml
      - platform/minikube.yaml

---

repositories:
  - name: skao
    url: https://artefact.skao.int/repository/helm-internal
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jupyterhub
    url: https://jupyterhub.github.io/helm-chart

releases:
  - name: ska-low-mccs-pasd
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: ../charts/ska-low-mccs-pasd
    version: ~0.8.0
    values:
      - values/globals.yaml.gotmpl
      - pasd/templates/fieldstations.yaml.gotmpl
      - pasd/templates/fndhs.yaml.gotmpl
      - pasd/templates/fnccs.yaml.gotmpl
      - pasd/templates/pasdbuses.yaml.gotmpl
      - pasd/templates/smartboxes.yaml.gotmpl
      - pasd/templates/pasdconfiguration.yaml.gotmpl
      - pasd/templates/helm-values.yaml.gotmpl

{{- $_tango_host_provided := dig "platform" "cluster" "services" "tango-base" "tango-host" "" .Values}}
{{- $tango_host_provided := dig "overrides" "cluster" "services" "tango-base" "tango-host" $_tango_host_provided .Values}}
{{- if not $tango_host_provided}}
  - name: ska-tango-base
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-base
    version: ~0.4.7
    values:
      - values/globals.yaml.gotmpl
{{- end}}

{{- $_jupyterhub_provided := dig "platform" "cluster" "services" "jupyterhub" false .Values}}
{{- $jupyterhub_provided := dig "overrides" "cluster" "services" "jupyterhub" $_jupyterhub_provided .Values}}
{{- if not $jupyterhub_provided}}
  - name: jupyterhub
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: jupyterhub/jupyterhub
    version: 3.0.0
    values:
      - values/jupyterhub.yaml.gotmpl
{{- end}}

{{- $_taranta_platform_provided := dig "platform" "cluster" "services" "taranta-platform" false .Values}}
{{- $taranta_platform_provided := dig "overrides" "cluster" "services" "taranta-platform" $_taranta_platform_provided .Values}}
{{- if not $taranta_platform_provided}}
  - name: taranta-dshbrd
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-taranta-dashboard
    version: 1.4.1
    values:
      - ingress:
          enabled: true
          hostname: "*"

  - name: taranta-dashboard-pvc
    namespace: ska-low-mccs
    chart: skao/ska-tango-taranta-dashboard-pvc
    version: 1.4.1

  - name: taranta-auth
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-taranta-auth
    version: ~0.1.9
    values:
      - ingress:
          enabled: true
          hostname: "*"
{{- end}}

  - name: taranta
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-taranta
    version: ~2.5.1
    values:
      - values/taranta.yaml

  - name: tangogql
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-tangogql
    version: ~1.3.10
    values:
      - values/globals.yaml.gotmpl
      - ska-tango-base:
          enabled: false
